# Generated by Django 2.1.7 on 2019-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_addition_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('s_price', models.FloatField()),
                ('l_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pastasalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('p_class', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
    ]
